name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: My-First-Step
        run: echo "Hello World!"
      
      - name: My-Second-Step
        run: echo "Hello, World!"

  runner-job:
    runs-on: master  # Mengganti 'master' menjadi 'self-hosted' jika Anda menggunakan runner di EC2
    steps:
      - name: Create a File
        run: echo "Hello World!" >> /home/ec2-user/test.txt

      - name: Display File Content
        run: cat /home/ec2-user/test.txt