name: My Workflow

on: push

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-first-step
        run: echo "Hello World!"

      - name: my-second-step
        run: edho "Hello World!"

  runner-jobs:
    my-workflow:
      runs-on: master
      steps:
        - name: my-fist-step
          run: echo "Hello, World!" >> /home/ec2-user/test.txt
        
        - name: my-first-step
          run: cat /home/ec2-user/test.txt

