name: My Worklof

on:
  push:
    branches:
      - main

jobs:
  my-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
      
      - name: Print Hello World
        run: echo "Hello, World!"

