name: My Workflow

on: push

jobs: 
  my-jobs:
    runs-on: ubuntu-latest
    steps: 
      -name: "Hello World"
       run: echo "Hello World"

      -name: "Hello World"
       run: echo "Hello World"