name: My Worklof

on:
  push:
    branches:
      - main

runner-jobs:
  my-workflow:
    runs-on: master
    steps:
      - name: my-fist-step
        run: echo "Hello, World!" >> /home/ec2-user/test.txt
      
      - name: my-fist-step
        run: cat /home/ec2-user/test.txt

